#SPDX-License-Identifier: MIT-0
---
# tasks file for app

- name: Create user
  become: yes
  ansible.builtin.user:
    name: cytech_usr
    password: $6$EPQiQm9hNpW5cR$Lns.1buPh2gOHFn7Js03yAxIpU69PAfQF4PwPUrIBUws5MCm9jUuFi/pBbrI/E6pQXU4PqIFNDVQAnh.UNL320
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/cytech_usr

- name: Installing Python
  become: yes
  ansible.builtin.apt:
    name:
      - acl
      - python3
      - python3-pip
      - python3-venv
      - oidentd

- name: Copy app folder
  become: yes
  become_user: cytech_usr
  ansible.builtin.copy:
    src: ../files/app
    dest: "{{home_path}}"
    mode: 'a+x'

- name: Create venv and install requirements
  become: yes
  become_user: cytech_usr
  pip:
    requirements: "{{appDir}}/requirements.txt"
    virtualenv: "{{venv_path}}"
    virtualenv_command: 'python3 -m venv'

- name: Apply template
  become: yes
  ansible.builtin.template:
    src: ../templates/app.service.j2
    dest: /etc/systemd/system/app.service

- name: Force systemd to reload files
  become: yes
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Setup services
  become: yes
  ansible.builtin.systemd_service:
    name: app
    state: restarted
    enabled: yes

- name: API request
  ansible.builtin.uri:
    url: http://localhost:8080/api/users
    return_content: true
  register: output

- name: Show result API request
  ansible.builtin.debug:
    var: output